sudo: required

language: scala

scala:
  - 2.11.6

services:
  - docker

env:
  global:
    - TERM=dumb

notifications:
  email: false

install: true

before_install:
  - ./tools/travis/setup.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_ff5bbb6225c5_key -iv $encrypted_ff5bbb6225c5_iv -in tests/credentials.json.enc -out tests/credentials.json -d; fi'
  - git clone --depth 1 https://github.com/apache/incubator-openwhisk.git openwhisk
  - cd openwhisk
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./tools/travis/setup.sh; fi'
  
script:
  - ./tools/travis/build.sh
